# Generated by Django 5.0.1 on 2024-01-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_ticket_blockedusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedusers',
            options={'verbose_name_plural': 'Blocked users'},
        ),
    ]
