version: "3.9"
   
services:
  db_p9:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
  web_p9:
    image: web_p9
    build: ./web_p9
    # command: bash -c "pwd && ls && python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}" 
    command: bash -c "pwd && ls && python manage.py migrate && python manage.py runserver 0.0.0.0:${WEB_PORT}" 
    volumes:
      - ./web_p9:/code
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      # - ${API_PORT}:${API_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
      - APP_NAME=Home
    depends_on:
      - db_p9

  adminer:
    container_name: adminer_p9
    image: dockette/adminer
    ports:
      - ${ADMINER_PORT}:80
    environment:
      - UPLOAD=4096M
      - MEMORY=512M

  
  # front: 
  #   build: ./canva-mozilla 
  #   # restart: always 
  #   # pour html -> port 80 : 
  #   ports: 
  #     - ${FRONT_PORT}:${FRONT_PORT} 

